# Generated by Django 4.2.1 on 2023-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='o', max_length=60, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Статья')),
            ],
        ),
    ]
